name: Checks
on:
    pull_request:
    push:
        branches:
            - "master"
            - "v[0-9]"
jobs:
    checks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.0', '8.1', '8.2', '8.3' ]
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -
                name: Install dependencies
                run: composer install --no-progress --prefer-dist --no-interaction
            -
                name: Run checks and tests
                run: composer check
